version: '3.7'
services:
  api1:
    image: tassan/rinha.api
    hostname: api1
    depends_on: 
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=mongodb://db:27017
    expose:
      - "80"
    deploy: 
      resources: 
        limits:
          cpus: '0.5'
          memory: '900MB'
          
  api2:
    image: tassan/rinha.api
    hostname: api2
    depends_on: 
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=mongodb://db:27017
    expose:
      - "80"
    deploy: 
      resources: 
        limits:
          cpus: '0.5'
          memory: '900MB'
    
  nginx:
    image: nginx:latest
    hostname: nginx
    depends_on: 
        - api1
        - api2
    ports:
      - "9999:9999"
    deploy: 
      resources: 
        limits:
          cpus: '0.25'
          memory: '500MB'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  db:
    image: mongo:latest
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    deploy:
      resources: 
          limits:
            cpus: '0.15'
            memory: '700MB'
  
networks:
  default:
    driver: bridge
    name: rinha
